---
apiVersion: v1
kind: Service
metadata:
  labels:
    project: piggymetrics
    tier: infrastructure
    app: rabbitmq
  name: rabbitmq
spec:
  ports:
  - name: http
    port: 15672
    targetPort: 15672
  - name: amqp
    port: 5672
    targetPort: 5672
  selector:
    project: piggymetrics
    tier: infrastructure
    app: rabbitmq
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    project: piggymetrics
    tier: infrastructure
    app: rabbitmq
  name: rabbitmq
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        project: piggymetrics
        tier: infrastructure
        app: rabbitmq
    spec:
      containers:
      - image: prasenforu/pig-rabbitmq:v1
        name: rabbitmq
        ports:
        - containerPort: 15672
        - containerPort: 5672
        resources: {}
      restartPolicy: Always
status: {}
