---
apiVersion: v1
kind: Service
metadata:
  labels:
    project: piggymetrics
    tier: infrastructure
    app: config
  name: config
spec:
  ports:
  - name: http
    port: 8888
    targetPort: 8888
  selector:
    project: piggymetrics
    tier: infrastructure
    app: config
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    project: piggymetrics
    tier: infrastructure
    app: config
  name: config
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:    
        project: piggymetrics
        tier: infrastructure
        app: config
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8686'        
    spec:
      containers:
      - env:
        - name: CONFIG_SERVICE_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: piggymetrics
              key: config_service_password
        image: prasenforu/pig-config:v1
        name: config
        ports:
        - containerPort: 8888
        resources: {}
      restartPolicy: Always
status: {}
