---
apiVersion: v1
kind: Service
metadata:
  name: statistics-mongodb
  labels:
    project: piggymetrics
    tier: database
    app: statistics-mongodb
spec:
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
  selector:
    project: piggymetrics
    tier: database
    app: statistics-mongodb
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    project: piggymetrics
    tier: database
    app: statistics-mongodb
  name: statistics-mongodb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        project: piggymetrics
        tier: database
        app: statistics-mongodb
    spec:
      containers:
      - env:
        - name: MONGODB_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: piggymetrics
              key: statistics_mongodb_password
        ports:
          - containerPort: 27017
        image: prasenforu/pig-mongodb:v1
        name: statistics-mongodb
        resources: {}
      restartPolicy: Always
status: {}
